grpcServer:
  port: 9001
program:
  - name: test
    directory: D:\DevSoftware\GolandProjects\agent\script
    command: test_script.bat
    isAutoStart: true
    isAutoRestart: true
    maxRestartCount: 4
    output: D:\DevSoftware\GolandProjects\agent\script\output.log